#Server settings (ServerProperties)
#server:
#  port: 8080
#  address: 127.0.0.1
#  session:
#    timeout: 30
#  context-path: /

  #Tomcat specifics
#  tomcat:
#    accesslog:
#      enabled: false
#    protocol-header: x-forwarded-proto
#    remote-ip-header: x-forwarded-for
#    background-processor-delay: 30 #secs
#    basedir:

service:
  info:
    title: Restful Web Service Example
    version: 1.0.0

logging:
  level:
    org.springframework.boot:INFO
    org.springframework.web:DEBUG
    org.springframework.data:INFO



spring:
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-title: org.h2.Driver
    #driver-class-title: com.mysql.jdbc.Driver
    url: jdbc:h2:mem:test
    #url: jdbc:mysql://localhost:3306/tw
    #username: root
    #password: rascal

#Flyway configuration
#flyway:
#  url: jdbc:mysql://localhost:3306/tw
#  #url: jdbc:h2:mem:test
#  user: root
#  password: rascal
#  enabled: true
#  baseline-on-migrate: true
#  table: schema_version
#  schemas[0]: tw
#  locations[0]: classpath:db/migration
#  out-of-order: true
#  encoding: UTF-8
#  #baseline-version: 1
#  sql-migration-prefix: V
